### PR TITLE
Update version 2.0.1 -> 2.0.2

### PR DESCRIPTION
**Pull request by dmlittle**
Upgrading wrapper version

### CODE REVIEW

**Comment by dmlittle** [comment]
@javadev how did you deploy to maven? I'm having credentials issues trying to deploy v2.0.2

**Comment by javadev** [comment]
I start maven clean install -Pdepliy, then archive all files in target directory with zip archive bandle.zip, then ligin to OS's, upload bundle and release it. Be sure that version contains only numbers without SNAPSHOT. Good luck. :)

**Comment by dmlittle** [comment]
@javadev could you deploy the new version 2.0.2? I don't have an OSS account. `master` branch has all the changes and updated version already.

**Comment by javadev** [comment]
Sure. ETA 10 mins.

**Comment by javadev** [comment]
Version 2.0.2 was released to the central maven repository.
We have a new release! 

2_0_2_release

**Pull request merged**
