### PR TITLE
Increase code coverage for the package com.lob.protocol.response.

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
All tests work for me: https://travis-ci.org/javadev/lob-java/builds/76973057

**Comment by javadev** [comment]
!

**Comment by javadev** [comment]
!

**Comment by shrav** [comment]
LGTM

**Comment by javadev** [comment]
This PR may be merged.

**Comment by javadev** [comment]
java.util.concurrent.TimeoutException: Request timed out to api.lob.com/54.214.13.187:443 of 60000 ms

**Comment by javadev** [comment]
!

**Pull request merged**
