### PR TITLE
Add patch to fix /etc/host on travis VM, change badges from png to svg.

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
I found an error in logs:

LobApiException: https://api.lob.com/v1/postcards 429: Rate limit exceeded. Please wait 60 seconds and try your request again.

**Comment by javadev** [comment]
!

**Comment by robinjoseph08** [comment]
Looks like we need to swap out the API key being used during in the test. I'll put that up in another PR, but my build won't pass without your `/etc/hosts` changes, so I'll be including those in that PR as well. Thanks for your help!

**Comment by javadev** [comment]
You are welcome. We also may move code coverage link from javadev to lob account.

**Pull request closed without merging**
